import type { Question } from "@/types/question";

export const sampleQuestions: Question[] = [
  {
    id: 1,
    uuid: "q-physics-001",
    question: "What is the SI unit of Force?",
    options: [
      { key: "A", value: "Joule", type: "text" },
      { key: "B", value: "Newton", type: "text" },
      { key: "C", value: "Pascal", type: "text" },
      { key: "D", value: "Watt", type: "text" },
    ],
    answer: "B",
    explanation: "Force is measured in Newton (N) according to SI units.",
    subjectId: 1,
    topicId: 1,
    subjectName: "Physics",
    topicName: "Mechanics",
    year: "2024",
    repeatedYears: ["2024"],
    repeatCount: 1,
    source: "past_year",
    importSource: "manual",
    difficulty: "easy",
    status: "published",
    media: {},
    aiTags: ["force", "SI unit", "mechanics"],
    aiReviewStatus: "approved",
    duplicateCheckStatus: "unique",
    possibleDuplicateIds: [],
    isMockEligible: true,
    createdAt: "2026-05-14",
    updatedAt: "2026-05-14",
  },
  {
    id: 2,
    uuid: "q-chemistry-001",
    question: "Which particle determines the atomic number of an element?",
    options: [
      { key: "A", value: "Electron", type: "text" },
      { key: "B", value: "Neutron", type: "text" },
      { key: "C", value: "Proton", type: "text" },
      { key: "D", value: "Nucleus", type: "text" },
    ],
    answer: "C",
    explanation: "Atomic number equals the number of protons present in the nucleus.",
    subjectId: 2,
    topicId: 3,
    subjectName: "Chemistry",
    topicName: "Atomic Structure",
    year: "2023",
    repeatedYears: ["2023"],
    repeatCount: 1,
    source: "past_year",
    importSource: "manual",
    difficulty: "medium",
    status: "published",
    media: {},
    aiTags: ["atom", "proton", "atomic number"],
    aiReviewStatus: "approved",
    duplicateCheckStatus: "unique",
    possibleDuplicateIds: [],
    isMockEligible: true,
    createdAt: "2026-05-14",
    updatedAt: "2026-05-14",
  },
  {
    id: 3,
    uuid: "q-zoology-001",
    question: "Which organelle is known as the powerhouse of the cell?",
    options: [
      { key: "A", value: "Ribosome", type: "text" },
      { key: "B", value: "Mitochondria", type: "text" },
      { key: "C", value: "Golgi body", type: "text" },
      { key: "D", value: "Nucleus", type: "text" },
    ],
    answer: "B",
    explanation: "Mitochondria produce ATP energy for cellular functions.",
    subjectId: 4,
    topicId: 6,
    subjectName: "Zoology",
    topicName: "Cell Biology",
    year: "2022",
    repeatedYears: ["2022"],
    repeatCount: 1,
    source: "past_year",
    importSource: "manual",
    difficulty: "easy",
    status: "published",
    media: {},
    aiTags: ["cell", "mitochondria", "ATP"],
    aiReviewStatus: "approved",
    duplicateCheckStatus: "unique",
    possibleDuplicateIds: [],
    isMockEligible: true,
    createdAt: "2026-05-14",
    updatedAt: "2026-05-14",
  },
];